### PR TITLE
Use unicorn instead of passenger

### PR DESCRIPTION
**Pull request by wzrdtales**
discourse lately removed the setting from the UI, this image doesn't really work properly without disabling this option currently.

Signed-off-by: Tobias Gurtzick <magic@wizardtales.com>

### CODE REVIEW

**Comment by wzrdtales** [comment]
somehow this doesn't seem to work. are those environment variables not passed to discourse?

**Comment by wzrdtales** [comment]
right now requires to set serve_static_assets = true

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by belmeopmenieuwesim** [comment]
this probably also fixes the issue in #59

**Comment by wzrdtales** [comment]
well dear bot, then make your team have some activity :)

**Comment by migruiz4** [comment]
Hi @wzrdtales,

I'm sorry for the late response, we didn't get notified about this PR due to an issue with our internal support tool.

Thank you very much for your contribution, I will try this out and get back to you, but I would like to ask you some questions:
- Is `runit` a requirement to run discourse with `unicorn`?
- In https://github.com/bitnami/bitnami-docker-discourse/issues/172, the workaround was to disable long polling, does unicorn not need that solution?
- Considering no additional dependencies are required, wouldn't it make sense to add an env variable so users can decide whether to use passenger or unicorn?

**Comment by belmeopmenieuwesim** [comment]
> Hi @wzrdtales,
> 
> I'm sorry for the late response, we didn't get notified about this PR due to an issue with our internal support tool.
> 
> Thank you very much for your contribution, I will try this out and get back to you, but I would like to ask you some questions:
> 
> * Is `runit` a requirement to run discourse with `unicorn`?
> * In [Request extremely slow sometimes #172](https://github.com/bitnami/bitnami-docker-discourse/issues/172), the workaround was to disable long polling, does unicorn not need that solution?
> * Considering no additional dependencies are required, wouldn't it make sense to add an env variable so users can decide whether to use passenger or unicorn?

Correct, long polling can be enabled just fine using unicorn. Also the official Discourse docker image also uses unicorn. Also `runit` is indeed required, I tried without it and it does ask for it.

**Comment by wzrdtales** [comment]
Unicorn is the official way to run discourse. Everything works as intended there

No it makes no sense since the passenger version is useless if you really want to run it in production.
And I guess runit is not a requirement but I took it from the original 

Sent from Nine

-- 

Best

--
Tobias Gurtzick
CEO
WizardTales GmbH

Additional Contacts:
@github | ***@***.***
--
Website: https://www.wizardtales.com
***@***.***
nmlpm: -- coming soon & open source --

Please tag your mails with "request", "issue" or "proposal", unless none of these fit or there already exists a thread.

-- Why should one reach for what one may be capable reaching, that's awfully boring and after all one still be ones yesterday being. --

Sitz der Gesellschaft: Ratingen
Kokkolastr. 5
40882 Ratingen
Germany

Registergericht: Amtsgericht Düsseldorf, HRB 84140
Geschäftsführer: Tobias Gurtzick

________________________________
Von: Miguel Ruiz ***@***.***>
Gesendet: Freitag, 1. Juli 2022 18:52
An: bitnami/bitnami-docker-discourse
Cc: Tobias Gurtzick; Mention
Betreff: Re: [bitnami/bitnami-docker-discourse] Use unicorn instead of passenger (PR #234) 

Hi @wzrdtales,
I'm sorry for the late response, we didn't get notified about this PR due to an issue with our internal support tool.
Thank you very much for your contribution, I will try this out and get back to you, but I would like to ask you some questions:
Is runit a requirement to run discourse with unicorn?
In #172, the workaround was to disable long polling, does unicorn not need that solution?
Considering no additional dependencies are required, wouldn't it make sense to add an env variable so users can decide whether to use passenger or unicorn?

**Comment by wzrdtales** [comment]
this bot is a troll

**Comment by migruiz4** [comment]
Hi @wzrdtales,

I tried to deploy Discourse with unicorn using the changes proposed in this PR, but I'm getting the following error:
```
discourse_1   | discourse 15:03:26.71 INFO  ==> ** Starting Discourse **
discourse_1   | supervisor pid: 1 unicorn pid: 473
discourse_1   | I, [2022-07-20T15:03:30.774434 #473]  INFO -- : Refreshing Gem list
discourse_1   | I, [2022-07-20T15:03:42.585598 #473]  INFO -- : listening on addr=127.0.0.1:3000 fd=7
discourse_1   | E, [2022-07-20T15:03:42.585844 #473] ERROR -- : adding listener failed addr=0.0.0.0:3000 (in use)
discourse_1   | E, [2022-07-20T15:03:42.585938 #473] ERROR -- : retrying in 0.5 seconds (4 tries left)
discourse_1   | E, [2022-07-20T15:03:43.087336 #473] ERROR -- : adding listener failed addr=0.0.0.0:3000 (in use)
discourse_1   | E, [2022-07-20T15:03:43.087529 #473] ERROR -- : retrying in 0.5 seconds (3 tries left)
discourse_1   | E, [2022-07-20T15:03:43.588549 #473] ERROR -- : adding listener failed addr=0.0.0.0:3000 (in use)
discourse_1   | E, [2022-07-20T15:03:43.588742 #473] ERROR -- : retrying in 0.5 seconds (2 tries left)
discourse_1   | E, [2022-07-20T15:03:44.089923 #473] ERROR -- : adding listener failed addr=0.0.0.0:3000 (in use)
discourse_1   | E, [2022-07-20T15:03:44.090239 #473] ERROR -- : retrying in 0.5 seconds (1 tries left)
discourse_1   | E, [2022-07-20T15:03:44.591419 #473] ERROR -- : adding listener failed addr=0.0.0.0:3000 (in use)
discourse_1   | E, [2022-07-20T15:03:44.591606 #473] ERROR -- : retrying in 0.5 seconds (0 tries left)
discourse_1   | E, [2022-07-20T15:03:45.092356 #473] ERROR -- : adding listener failed addr=0.0.0.0:3000 (in use)
discourse_1   | /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/socket_helper.rb:165:in `bind': Address already in use - bind(2) for 0.0.0.0:3000 (Errno::EADDRINUSE)
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/socket_helper.rb:165:in `new_tcp_server'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/socket_helper.rb:145:in `bind_listen'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:242:in `listen'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:877:in `block in bind_new_listeners!'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:877:in `each'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:877:in `bind_new_listeners!'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:141:in `start'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/bin/unicorn:25:in `load'
discourse_1   |         from /opt/bitnami/discourse/vendor/bundle/ruby/2.7.0/bin/unicorn:25:in `<main>'
discourse_1   | config/unicorn_launcher: line 71: kill: (473) - No such process
discourse_1   | config/unicorn_launcher: line 15: kill: (473) - No such process
discourse_1   | (1) exiting
debian-10_discourse_1 exited with code 0
```

These are the steps I used in case you'd like to reproduce the exact same deployment:
```
git clone https://github.com/bitnami/bitnami-docker-discourse
cd bitnami-docker-discourse
git fetch origin "pull/234/head:pr-234"
git checkout pr-234 
cd 2/debian-10/
docker build -t bitnami/discourse:development .
sed -i 's|bitnami/discourse:2|bitnami/discourse:development|' docker-compose.yml
docker-compose down -v
docker-compose up
```

**Comment by wzrdtales** [comment]
the docker-compose seems to be outdated and deviates from the helm chart.
The helm chart sets already

```
  - DISCOURSE_PORT_NUMBER=8080
  - DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER=80
```

These two variables, and adding those to the docker-compose lets it run just fine.

**Comment by carrodher** [comment]
In order to unify the approaches followed for Bitnami containers and Bitnami Helm charts, we are moving the different `bitnami/bitnami-docker-<container>` repositories to a single repository: `bitnami/containers`.

Please could you create this PR in the [`bitnami/containers` monorepository](https://github.com/bitnami/containers)? Thank

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

**Pull request closed without merging**
