### PR TITLE
Sets POSTGRESQL_CLIENT_CREATE_* to reasonable defaults.

### PR DESCRIPTION
**Pull request by MicahZoltu**
This may have unintended consequences, but out of the box `docker-compose up` didn't work until I set these, so it seems reasonable to just bake in reasonable defaults that will "just work" and allow users to override them.

My fear with this PR is that the system is not resilient and if those are set on every service start it will blow away and recreate the database or something, which is why they were left out.  If that isn't the case, then this PR is probably reasonable and will help mitigate failures like the one I experienced.

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

### CODE REVIEW

**Comment by tompizmor** [comment]
Hi @MicahZoltu,

I don't think we need to set default values for the database parameters.
You would have to know the postgres root password so I don't think that you can just set a default value for this parameter that will just work out-of-the-box as it will depend on the user password.

**Comment by MicahZoltu** [comment]
The user can, of course, override these if they use an external database or set the POSTGRES database username/password themselves.  The idea here is to make it so `docker-compose up` "just works" out of the box, and from there the user can tune the settings as they see fit.

Perhaps a better option would be to have these set in the docker-compose file instead?  Thinking more on it, that seems like a prudent solution as it makes it more apparent to the user that default passwords are being used (and should be changed).

**Comment by tompizmor** [comment]
> Perhaps a better option would be to have these set in the docker-compose file instead? 

Aren't they already specified in the docker-compose file? I see default values specified here:

https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-9/docker-compose.yml#L25-L27 

>  The idea here is to make it so docker-compose up "just works" out of the box, and from there the user can tune the settings as they see fit.

This [docker-compose file](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-9/docker-compose.yml) works as it is for me. Is the one you are trying to deploy? Can you share your docker-compose file with me?

**Comment by MicahZoltu** [comment]
Hmm, you are right.  I'm going to chalk this up to "I must have been doing something else wrong" at the time when I created this issue.  Sorry!

**Comment by tompizmor** [comment]
Don't worry!

**Pull request closed without merging**
