### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by cheungtitus**
Per following Discourse is supported to run only on PostgreSQL 12 or later.
https://meta.discourse.org/t/running-discourse-with-a-separate-postgresql-server/46375

This is confirmed to be the case with the latest official Discourse Docker pulled.
```bash
[root@uat ~]# docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                                      NAMES
edfc85d4ac22        local_discourse/app   "/sbin/boot"        7 days ago          Up 7 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   app
[root@uat ~]#
[root@uat ~]# docker exec -it app bash
root@uat-app:/#
root@uat-app:/# /usr/lib/postgresql/12/bin/postgres -V
postgres (PostgreSQL) 12.4 (Debian 12.4-1.pgdg100+1)
```

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the PR! We would like to perform the changes in both the docker-compose and the chart, so we may need to hold this PR until everything is ready.

**Comment by cheungtitus** [comment]
> Hi,
> 
> Thank you so much for the PR! We would like to perform the changes in both the docker-compose and the chart, so we may need to hold this PR until everything is ready.

@javsalgar thanks for the comment.  Not sure where the Bitnami code is hosted for building the update to repo like this but probably worth adding additional logic to check the dependencies bundled with the latest source.  The complexity for this specific case is Discourse's Docker image comes with Redis, Postgres, Sidekiq all within the same docker image so if we pull the latest Discourse's Docker image it'd already have all these dependencies updated if they need to.  Bitnami's approach is to separate these out into individual containers hence there is a risk to not update the dependencies.

**Comment by markbaird** [comment]
The version of Postgres in the Docker image, specified in the `Dockerfile`, also needs to be updated. Discourse calls `pgdump` as part of its automated backup process and if you try to run the current image against a Postgres 12 database, you get a version mismatch error which prevents backups.

**Comment by javsalgar** [comment]
Hi,

Thanks for the input. I will forward this to the team for re-prioritization. I will update when I have more details.

**Comment by noplanman** [comment]
@javsalgar Any update on this, I'm running into the problem that @markbaird mentioned above, the version mismatch of `pg_dump`.

Related issue: #159

**Comment by javsalgar** [comment]
Hi,

It is still in our backlog. However, I we re-prioritized the task and we expect to work on it in our next spring.

**Comment by carrodher** [comment]
In order to unify the approaches followed for Bitnami containers and Bitnami Helm charts, we are moving the different `bitnami/bitnami-docker-<container>` repositories to a single repository: `bitnami/containers`.

Please could you create this PR in the [`bitnami/containers` monorepository](https://github.com/bitnami/containers)? Thank

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

**Pull request closed without merging**
