### PR TITLE
Version changed and cant be downloaded

### PR DESCRIPTION
**Pull request by ArtHoffmann**
Hi, edit pls the version of ruby.. the version 2.7.5 is not available for download

old: https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.5-x86_64-linux.tar.gz

new: https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.7.4-x86_64-linux.tar.gz

### CODE REVIEW

**Comment by ArtHoffmann** [comment]
[](https://github.com/ArtHoffmann)[ArtHoffmann](https://github.com/ArtHoffmann)
 
ArtHoffmann commented [now](https://github.com/bitnami/bitnami-docker-discourse/pull/225#issue-1158777969)

**Comment by migruiz4** [comment]
Hi @ArtHoffmann,

I'm sorry but we are not downloading our binaries from that source. 
We compile Ruby from sources and publish it here, where the Dockerfile will download it: https://downloads.bitnami.com/files/stacksmith/ruby-2.7.5-35-linux-amd64-debian-10.tar.gz

You can find the logic used to download the components at https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/prebuildfs/opt/bitnami/scripts/libcomponent.sh

**Comment by migruiz4** [comment]
Hi @ArtHoffmann,

We are looking into this issue. But in order to fix it, we need to perform some internal actions to rebuild Discourse, therefore I can not accept this PR.

We can continue with this discussion here: https://github.com/bitnami/bitnami-docker-discourse/issues/59

**Comment by marcosbc** [comment]
Hi @ArtHoffmann, Discourse [2.8.1-debian-10-r0](https://github.com/bitnami/bitnami-docker-discourse/commit/e72541b481ff1d266766cbbcc72fade87a094c11) was just released with a fix for this issue.

**Pull request closed without merging**
